server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://rakindumarambe17_db_user:dbuser@cluster0.wctupda.mongodb.net/user_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
