server:
  port: 8084

spring:
  application:
    name: po-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/po_db}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
